# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d6f92725a22c097177a7e30500b211f3c88736203d5784529c4bbc8c86aed30e5d3f0dc99a854fabb2732d676a3cab1b5e860151af9b5edb6001368b9a95880

test:
  secret_key_base: 948213ccab256463a2ecc633dd19448df8cc80f7c74550e95c7653105d722afcc5577524b555df7e276a85581434273cf966f010927289c67662f765a3801c49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
